### PR TITLE
allow alpha to be customised in config

### PR DESCRIPTION
**Pull request by jokeyrhyme**
### Added

-   new `config.hyperTransparentDynamic` section in hyper.js settings file

-   new `config.hyperTransparentDynamic.alpha` option to customise alpha transparency

### CODE REVIEW

**Comment by jonathantneal** [comment]
This is the missing feature.

**Comment by jokeyrhyme** [comment]
@magus  ? any guidance as to what you'd like to see before this gets merged?

**Comment by magus** [comment]
Thanks for the contribution!

**Comment by jokeyrhyme** [comment]
@magus Awesome! Were you able to bump the version and do a new `npm publish`? Or did you have other changes that you wanted to do first?

**Comment by magus** [comment]
Published as 1.2.0!

**Pull request merged**
